(function () {
  const courses = [
    { id: "intro-ing", name: "Introduccion a la Ingenieria", year: 1, semester: 1, prerequisites: [] },
    { id: "intro-prog", name: "Introduccion a la Programacion", year: 1, semester: 1, prerequisites: [] },
    { id: "mat-i", name: "Matematica I", year: 1, semester: 1, prerequisites: [] },
    { id: "eco-i", name: "Economia I", year: 1, semester: 1, prerequisites: [] },
    { id: "algebra", name: "Algebra y Geometria Analitica", year: 1, semester: 2, prerequisites: ["mat-i"] },
    { id: "quimica", name: "Quimica General", year: 1, semester: 2, prerequisites: [] },
    { id: "mat-ii", name: "Matematica II", year: 1, semester: 2, prerequisites: ["mat-i"] },
    { id: "humanidades", name: "Electiva en Humanidades o Ciencias Sociales", year: 1, semester: 2, prerequisites: [] },
    { id: "estadistica-intro", name: "Introduccion a la Estadistica", year: 2, semester: 1, prerequisites: ["mat-ii"] },
    { id: "fisica-i", name: "Fisica I", year: 2, semester: 1, prerequisites: ["mat-ii", "algebra"] },
    { id: "mat-iii", name: "Matematica III", year: 2, semester: 1, prerequisites: ["mat-ii", "algebra"] },
    { id: "algoritmos", name: "Algoritmos y Estructuras de Datos", year: 2, semester: 1, prerequisites: ["intro-prog"] },
    { id: "inferencia", name: "Inferencia Estadistica", year: 2, semester: 2, prerequisites: ["estadistica-intro"] },
    { id: "fisica-ii", name: "Fisica II", year: 2, semester: 2, prerequisites: ["fisica-i", "mat-iii"] },
    { id: "mecatronico-i", name: "Diseno Mecatronico I", year: 2, semester: 2, prerequisites: ["fisica-i", "algoritmos"] },
    { id: "microeconomia", name: "Microeconomia", year: 2, semester: 2, prerequisites: ["eco-i"] },
    { id: "industrias-i", name: "Ingenieria de Industrias I: Produccion y Procesos", year: 3, semester: 1, prerequisites: ["intro-ing", "fisica-ii", "quimica"] },
    { id: "fisica-iii", name: "Fisica III", year: 3, semester: 1, prerequisites: ["fisica-ii", "mat-iii"] },
    { id: "electrica", name: "Tecnologia Electrica y Electronica", year: 3, semester: 1, prerequisites: ["fisica-ii"] },
    { id: "mat-aplicada", name: "Matematica Aplicada", year: 3, semester: 1, prerequisites: ["mat-iii", "inferencia"] },
    { id: "industrias-ii", name: "Ingenieria de Industrias II: Investigacion Operativa", year: 3, semester: 2, prerequisites: ["industrias-i", "mat-aplicada"] },
    { id: "termo-fluidos", name: "Termodinamica y Mecanica de Fluidos", year: 3, semester: 2, prerequisites: ["fisica-ii", "quimica"] },
    { id: "mecatronico-ii", name: "Diseno Mecatronico II", year: 3, semester: 2, prerequisites: ["mecatronico-i", "electrica"] },
    { id: "contabilidad", name: "Introduccion a la Contabilidad y las Finanzas", year: 3, semester: 2, prerequisites: ["microeconomia"] },
    { id: "industrias-iii", name: "Ingenieria de Industrias III: Planificacion y Logistica", year: 4, semester: 1, prerequisites: ["industrias-ii"] },
    { id: "energia", name: "Ingenieria de la Energia", year: 4, semester: 1, prerequisites: ["termo-fluidos", "electrica"] },
    { id: "mecatronico-iii", name: "Diseno Mecatronico III", year: 4, semester: 1, prerequisites: ["mecatronico-ii"] },
    { id: "materiales", name: "Ciencia de Materiales", year: 4, semester: 1, prerequisites: ["quimica", "fisica-ii"] },
    { id: "sistemas-gestion", name: "Ingenieria de Industrias: Sistemas y Gestion", year: 4, semester: 2, prerequisites: ["industrias-iii", "contabilidad"] },
    { id: "datos-bi", name: "Datos e Inteligencia de Negocios", year: 4, semester: 2, prerequisites: ["inferencia", "algoritmos"] },
    { id: "instalaciones", name: "Instalaciones y Procesos Industriales", year: 4, semester: 2, prerequisites: ["energia", "materiales"] },
    { id: "electiva-conc-1", name: "Electiva en concentracion elegida", year: 4, semester: 2, prerequisites: ["industrias-ii"] },
    { id: "innovacion", name: "Innovacion y Sostenibilidad", year: 5, semester: 1, prerequisites: ["sistemas-gestion"] },
    { id: "liderazgo", name: "Equipos y Liderazgo", year: 5, semester: 1, prerequisites: ["industrias-iii"] },
    { id: "etica", name: "Etica y Legislacion", year: 5, semester: 1, prerequisites: ["contabilidad"] },
    { id: "campo-menor-1", name: "Curso electivo o de campo menor", year: 5, semester: 1, prerequisites: ["industrias-ii"] },
    { id: "electiva-conc-2", name: "Electiva en concentracion elegida", year: 5, semester: 1, prerequisites: ["electiva-conc-1"] },
    { id: "proyecto-final", name: "Proyecto Final de Ingenieria Industrial", year: 5, semester: 2, prerequisites: ["sistemas-gestion", "datos-bi", "instalaciones", "innovacion", "etica"] },
    { id: "campo-menor-2", name: "Curso electivo o de campo menor", year: 5, semester: 2, prerequisites: ["campo-menor-1"] },
    { id: "campo-menor-3", name: "Curso electivo o de campo menor", year: 5, semester: 2, prerequisites: ["campo-menor-1"] },
    { id: "electiva-conc-3", name: "Electiva en concentracion elegida", year: 5, semester: 2, prerequisites: ["electiva-conc-2"] },
    { id: "pps", name: "Practica Profesional Supervisada", year: 5, semester: 2, prerequisites: ["sistemas-gestion", "instalaciones", "liderazgo"] },
  ];

  window.CURRICULUM = courses;
})();
